# Generated by Django 5.2.6 on 2025-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.CharField(max_length=255, unique=True)),
                ('calendarId', models.CharField(max_length=255)),
                ('contactId', models.CharField(max_length=255)),
                ('locationId', models.CharField(blank=True, max_length=255, null=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
